### PR TITLE
`ImageInTerminal` 0.5

### PR DESCRIPTION
**Pull request by t-bltg**
circular dep (bump patch needed).

### CODE REVIEW

**Comment by t-bltg** [comment]
Thanks !

**Comment by johnnychen94** [comment]
Oops, actually this will be a breaking change since how text image is encoded is changed (reference test will fail).

I'll watch if people hit this issue and see if we need fixes somewhere.

**Comment by t-bltg** [comment]
I'll keep an eye on that too.

**Comment by oxinabox** [comment]
oops, sorry.
My bad i should have waited til CI finished before merging.

**Comment by t-bltg** [comment]
>  My bad i should have waited til CI finished before merging.

Not your fault this was induced by the circular dependency and is clearly a corner case !

**Pull request merged**
